-- Durable SSE event history and one-time stream authentication shared by all workers.
-- Run once in the Supabase SQL editor before enabling cross-worker SSE.

create table if not exists sse_events (
  id bigint generated by default as identity primary key,
  job_id text not null,
  user_id text,
  event_data jsonb not null,
  created_at timestamptz not null default now()
);

alter table sse_events
  add column if not exists user_id text;

create index if not exists sse_events_job_user_id_id_idx
  on sse_events (job_id, user_id, id);

create index if not exists sse_events_created_at_idx
  on sse_events (created_at);

alter table sse_events enable row level security;

revoke all on table sse_events from anon;
grant select on table sse_events to authenticated;

drop policy if exists "Authenticated users can read their own SSE events" on sse_events;
create policy "Authenticated users can read their own SSE events"
  on sse_events
  for select
  to authenticated
  using ((select auth.uid()::text) = user_id);

create table if not exists sse_stream_tokens (
  token_hash text primary key,
  user_id text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists sse_stream_tokens_expires_at_idx
  on sse_stream_tokens (expires_at);

alter table sse_stream_tokens enable row level security;

revoke all on table sse_stream_tokens from anon, authenticated;
