-- Durable SSE event history and one-time stream authentication shared by all workers.
-- Run once in the Supabase SQL editor before enabling cross-worker SSE.

create table if not exists sse_events (
  id bigint generated by default as identity primary key,
  job_id text not null,
  user_id text,
  event_data jsonb not null,
  created_at timestamptz not null default now()
);

alter table sse_events
  add column if not exists user_id text;

create index if not exists sse_events_job_user_id_id_idx
  on sse_events (job_id, user_id, id);

create index if not exists sse_events_created_at_idx
  on sse_events (created_at);

alter table sse_events enable row level security;

drop policy if exists "Service role can manage SSE events" on sse_events;
create policy "Service role can manage SSE events"
  on sse_events
  for all
  to service_role
  using (true)
  with check (true);

create table if not exists sse_stream_tokens (
  token_hash text primary key,
  user_id text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists sse_stream_tokens_expires_at_idx
  on sse_stream_tokens (expires_at);

alter table sse_stream_tokens enable row level security;

drop policy if exists "Service role can manage SSE stream tokens" on sse_stream_tokens;
create policy "Service role can manage SSE stream tokens"
  on sse_stream_tokens
  for all
  to service_role
  using (true)
  with check (true);
